// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package yu.co.certus.sms;

public final class SmsServer_Stub
    extends java.rmi.server.RemoteStub
    implements yu.co.certus.sms.ISmsServer, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_exit_0;
    private static java.lang.reflect.Method $method_sendMessage_1;
    
    static {
	try {
	    $method_exit_0 = yu.co.certus.sms.ISmsServer.class.getMethod("exit", new java.lang.Class[] {});
	    $method_sendMessage_1 = yu.co.certus.sms.ISmsServer.class.getMethod("sendMessage", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public SmsServer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of exit()
    public void exit()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_exit_0, null, -6307240473358936408L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sendMessage(String, String)
    public void sendMessage(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_sendMessage_1, new java.lang.Object[] {$param_String_1, $param_String_2}, 6986607928290535307L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
